### PR TITLE
Development changes to get things working

### PR DESCRIPTION
**Pull request by Ares42**
I noticed that the project wasn't building, and spent some time working on this to fix it. Feel free to look over the changes and see if anything I did was bad/incorrect/silly. This is my first time committing to an open source repo, so your feedback is appreciated!

### CODE REVIEW

**Comment by Ares42** [comment]
Bumping this...hopefully someone takes a look at it!

**Comment by tomtaylor** [comment]
@ares42 thanks for this, I'm sorry I haven't responded sooner. I haven't had a chance to properly look at this, but will over the weekend. However, it's difficult to merge as is, because the commits are a jumble of changes, and could do with reworking to make the history clearer. Do you think you could tidy this up?

**Comment by hugovk** [comment]
@tomtaylor One option to tidy up history is "squash and merge":

image

**Comment by tomtaylor** [comment]
I'm going to have to close this, as it has too many loose ends, such as disabling the entire launch at login system, and custom paths for the workspace. I've started work in #61 to build properly on Xcode 8.2.

**Pull request closed without merging**
