### PR TITLE
Add a dark 'blueprint' effect

### PR DESCRIPTION
**Pull request by randomsequence**
Inverts the image, applies false colour and a vingette.

* TTMapImage gains the ability to read colours from the filters in the defaults array.
* TTMapImage respects a boolean key `disableAffineClamp` in the filter dictionary. Vignette doesn't work with AffineClamp in place.

Preview:
map-97065e939d5f97c95af4986b66c9f697

Ref tomtaylor/satellite-eyes#34

### CODE REVIEW

**Comment by tomtaylor** [comment]
Sorry it's taken so long to review this. It's really nice, but depends heavily on the contrast of the satellite imagery. With the imagery near my house, it's difficult to make out any outline on the blueprint, because the contrast is quite low.

I'm not sure of the best way of approaching this. Any suggestions?

map-fffc3f13fc1d48079be4b9d5ed453ef7

**Comment by randomsequence** [comment]
The only sensible suggestion I have is to parameterise the effects, as per the Quartz Composer experiments above.

My work commitments have changed lately, so I'm unlikely to be able to contribute to that any further just now.

**Comment by tomtaylor** [comment]
Thanks @randomsequence - let's leave this for now. I like the idea of parameterising the effects, but it's probably more than I can take on now either. If anyone else wants to take this on, that'd be great!

**Comment by bobthecow** [comment]
There are other effects that don't work well with satellite imagery. I don't know that it's worth not merging this just because it doesn't work for your house ;)

**Comment by tomtaylor** [comment]
Hah, no, sure! I just wasn't sure how widespread low contrast imagery was, and whether it needed some tuning, etc. I really like the effect.

**Pull request closed without merging**
